# Generated by Django 4.0.4 on 2022-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_despesa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevistos'), ('O', 'Outras')], default='Outras', max_length=200),
        ),
    ]
